# Tema 1- Matrices

Vamos a ver cómo crear una matriz utilizando la librería `numpy`

In [2]:
row = [1, 2, 3]
row

[1, 2, 3]

In [3]:
col = [[1], [2], [3]]
col

[[1], [2], [3]]

In [4]:
M = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
M

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
M[1][1]

5

In [6]:
M[0][0]

1

In [7]:
M[0]

[1, 2, 3]

In [41]:
for row in M:
    print(row[0])

1.0
4.0
7.0


In [8]:
2 * M

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
import numpy as np

In [14]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype = float)

In [15]:
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [16]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.shape(M)

(3, 3)

In [23]:
A = np.array([[1, 2], [3, 4]])
print(A)
B = np.array([[3, 0], [1, -1]])
print(B)

[[1 2]
 [3 4]]
[[ 3  0]
 [ 1 -1]]


In [24]:
print(A + B)

[[4 2]
 [4 3]]


In [25]:
print(A.dot(B))

[[ 5 -2]
 [13 -4]]


In [26]:
print(A.transpose())

[[1 3]
 [2 4]]


In [27]:
print(A.trace())

5


In [28]:
np.linalg.matrix_rank(A)

2

In [29]:
np.linalg.matrix_power(A, 5)

array([[1069, 1558],
       [2337, 3406]])

In [30]:
np.linalg.det(A)

-2.0000000000000004

In [31]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [32]:
np.linalg.inv(A).dot(A)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [35]:
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [36]:
np.linalg.det(X)

6.66133814775094e-16

In [37]:
np.linalg.matrix_rank(X)

2

In [38]:
np.linalg.inv(X)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

No se nos ocurrirá nunca hacer la inversa ni de una matriz cuadrada, ni de una matriz cuyo rango sea inferior a su orden (el número de filas / columnas de la misma).

In [40]:
# np.linalg.inv(np.array([1, 2, 3], [4, 5, 6]))